# Generated by Django 3.2.2 on 2022-11-30 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=60, verbose_name='first name')),
                ('last_name', models.CharField(max_length=60, verbose_name='last name')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('bitcoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('bitcoin_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('ethereum_address', models.CharField(blank=True, max_length=200, null=True)),
                ('ethereum_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('litecoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('litecoin_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('bitcoincash_address', models.CharField(blank=True, max_length=200, null=True)),
                ('bitcoincash_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('binance_address', models.CharField(blank=True, max_length=200, null=True)),
                ('binance_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('dogecoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('dogecoin_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('dashcoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('dashcoin_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('usdt_trc20_address', models.CharField(blank=True, max_length=200, null=True)),
                ('usdt_trc20_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('usdt_erc20_address', models.CharField(blank=True, max_length=200, null=True)),
                ('usdt_erc20_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('usdt_bep20_address', models.CharField(blank=True, max_length=200, null=True)),
                ('usdt_bep20_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('busd_address', models.CharField(blank=True, max_length=200, null=True)),
                ('busd_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('tron_address', models.CharField(blank=True, max_length=200, null=True)),
                ('tron_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('xrp_address', models.CharField(blank=True, max_length=200, null=True)),
                ('xrp_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('solana_address', models.CharField(blank=True, max_length=200, null=True)),
                ('solana_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('cordano_address', models.CharField(blank=True, max_length=200, null=True)),
                ('cordano_qrcode', models.ImageField(blank=True, null=True, upload_to='images/company')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=3000)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=25, unique=True)),
                ('daily_profit_percentage', models.FloatField(help_text='in percentage(%)')),
                ('minimum_amount', models.PositiveIntegerField()),
                ('maximum_amount', models.PositiveIntegerField()),
                ('referral_commission', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)], default=10)),
                ('duration_in_days', models.PositiveSmallIntegerField(help_text='in_days')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disapproved', 'disapproved'), ('completed', 'completed')], default='deposit', max_length=30)),
                ('payment_method', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
                ('payment_address', models.CharField(max_length=60)),
                ('network', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disapproved', 'disapproved'), ('completed', 'completed')], default='pending', max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profiles')),
                ('ref_code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='referral code')),
                ('downlines', models.ManyToManyField(related_name='downline', to=settings.AUTH_USER_MODEL, verbose_name='referred')),
                ('upline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upline', to=settings.AUTH_USER_MODEL, verbose_name='upline')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.CharField(max_length=12)),
                ('payment_method', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miningapp.package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('referral_bonus', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
