# Generated by Django 3.2.2 on 2022-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningapp', '0003_auto_20221202_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='completed',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw')], default='withdraw', max_length=30),
        ),
    ]
