# Generated by Django 3.2.2 on 2022-12-03 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningapp', '0004_auto_20221203_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='downlines',
            field=models.ManyToManyField(blank=True, related_name='downline', to=settings.AUTH_USER_MODEL, verbose_name='referred'),
        ),
    ]
