# Generated by Django 3.2.2 on 2022-12-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningapp', '0007_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
