# Generated by Django 3.2.2 on 2022-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningapp', '0008_auto_20221209_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='referral_bonus',
            new_name='referral_balance',
        ),
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='This field is calculated and depends on approved date', null=True),
        ),
    ]
