# Generated by Django 3.2.2 on 2010-01-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningapp', '0011_auto_20221220_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='referral_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returns',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='country/state', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.FloatField(),
        ),
    ]
