# Generated by Django 3.2.2 on 2022-12-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningapp', '0013_auto_20221223_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='daily_profit_percentage',
            field=models.DecimalField(decimal_places=1, help_text='in percentage(%)', max_digits=3),
        ),
    ]
