# Generated by Django 3.2.2 on 2022-12-25 23:30

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningapp', '0014_alter_package_daily_profit_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='binance_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='bitcoin_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='bitcoincash_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='busd_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='cordano_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='dashcoin_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='dogecoin_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='ethereum_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='litecoin_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='solana_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tron_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='usdt_bep20_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='usdt_erc20_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='usdt_trc20_qrcode',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='xrp_qrcode',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images/company'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='document',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='document'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='site_domain',
            field=models.CharField(default=2, help_text='site url/link i.e miningsite.com', max_length=150),
            preserve_default=False,
        ),
    ]
